### ISSUE TITLE
[Request] Make papaya hud to appear only on the gamepad instead of both screens.

### ISSUE THREAD

**Issue by ItsPancho8** [dkosmari/Papaya-HUD#1]
I feel that the hud on the main screen is invasive, and considering that it appears on both monitor/tv and the gamepad, I think that making a option to make it appear in only one of the screens could be very good.

**Comment by dkosmari** [comment]
It's not possible right now, as it uses the Notifications module to show the HUD, with a persistent notification. We don't have this level of control.

The plan is to have dedicated HUD rendering code later, with full control of what is rendered and where.

**Comment by ItsPancho8** [comment]
Oh I see, I wish you good luck with the project and your plans with it, I really like your plugin.
